package co.com.ordersAgiles.entidades;
// Generated 27/02/2015 01:39:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ordart generated by hbm2java
 */
public class Ordart  implements java.io.Serializable {


     private long id;
     private Ordktg ordktg;
     private String descripcion;
     private Integer estado;
     private Double iva;
     private Double ivaPtj;
     private String marca;
     private String modelo;
     private String nombre;
     private String observaciones;
     private Double valorUnit;
     private String imagen;
     private String codigoBarra;
     private Set<Orddtl> orddtls = new HashSet<Orddtl>(0);
     private Set<Ordinv> ordinvs = new HashSet<Ordinv>(0);

    public Ordart() {
    }

	
    public Ordart(long id) {
        this.id = id;
    }
    public Ordart(long id, Ordktg ordktg, String descripcion, Integer estado, Double iva, Double ivaPtj, String marca, String modelo, String nombre, String observaciones, Double valorUnit, String imagen, String codigoBarra, Set<Orddtl> orddtls, Set<Ordinv> ordinvs) {
       this.id = id;
       this.ordktg = ordktg;
       this.descripcion = descripcion;
       this.estado = estado;
       this.iva = iva;
       this.ivaPtj = ivaPtj;
       this.marca = marca;
       this.modelo = modelo;
       this.nombre = nombre;
       this.observaciones = observaciones;
       this.valorUnit = valorUnit;
       this.imagen = imagen;
       this.codigoBarra = codigoBarra;
       this.orddtls = orddtls;
       this.ordinvs = ordinvs;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Ordktg getOrdktg() {
        return this.ordktg;
    }
    
    public void setOrdktg(Ordktg ordktg) {
        this.ordktg = ordktg;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Double getIva() {
        return this.iva;
    }
    
    public void setIva(Double iva) {
        this.iva = iva;
    }
    public Double getIvaPtj() {
        return this.ivaPtj;
    }
    
    public void setIvaPtj(Double ivaPtj) {
        this.ivaPtj = ivaPtj;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Double getValorUnit() {
        return this.valorUnit;
    }
    
    public void setValorUnit(Double valorUnit) {
        this.valorUnit = valorUnit;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public String getCodigoBarra() {
        return this.codigoBarra;
    }
    
    public void setCodigoBarra(String codigoBarra) {
        this.codigoBarra = codigoBarra;
    }
    public Set<Orddtl> getOrddtls() {
        return this.orddtls;
    }
    
    public void setOrddtls(Set<Orddtl> orddtls) {
        this.orddtls = orddtls;
    }
    public Set<Ordinv> getOrdinvs() {
        return this.ordinvs;
    }
    
    public void setOrdinvs(Set<Ordinv> ordinvs) {
        this.ordinvs = ordinvs;
    }




}


