package co.com.ordersAgiles.entidades;
// Generated 27/02/2015 01:39:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ordarq generated by hbm2java
 */
public class Ordarq  implements java.io.Serializable {


     private long id;
     private Ordkja ordkja;
     private Ordusr ordusrByUsuarioapertura;
     private Ordusr ordusrByUsuariocierre;
     private Double descuadre;
     private Integer estado;
     private Date fechaapertura;
     private Date fechacierre;
     private Double valorapertura;
     private Double valorcierre;
     private Double salidas;

    public Ordarq() {
    }

	
    public Ordarq(long id) {
        this.id = id;
    }
    public Ordarq(long id, Ordkja ordkja, Ordusr ordusrByUsuarioapertura, Ordusr ordusrByUsuariocierre, Double descuadre, Integer estado, Date fechaapertura, Date fechacierre, Double valorapertura, Double valorcierre, Double salidas) {
       this.id = id;
       this.ordkja = ordkja;
       this.ordusrByUsuarioapertura = ordusrByUsuarioapertura;
       this.ordusrByUsuariocierre = ordusrByUsuariocierre;
       this.descuadre = descuadre;
       this.estado = estado;
       this.fechaapertura = fechaapertura;
       this.fechacierre = fechacierre;
       this.valorapertura = valorapertura;
       this.valorcierre = valorcierre;
       this.salidas = salidas;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Ordkja getOrdkja() {
        return this.ordkja;
    }
    
    public void setOrdkja(Ordkja ordkja) {
        this.ordkja = ordkja;
    }
    public Ordusr getOrdusrByUsuarioapertura() {
        return this.ordusrByUsuarioapertura;
    }
    
    public void setOrdusrByUsuarioapertura(Ordusr ordusrByUsuarioapertura) {
        this.ordusrByUsuarioapertura = ordusrByUsuarioapertura;
    }
    public Ordusr getOrdusrByUsuariocierre() {
        return this.ordusrByUsuariocierre;
    }
    
    public void setOrdusrByUsuariocierre(Ordusr ordusrByUsuariocierre) {
        this.ordusrByUsuariocierre = ordusrByUsuariocierre;
    }
    public Double getDescuadre() {
        return this.descuadre;
    }
    
    public void setDescuadre(Double descuadre) {
        this.descuadre = descuadre;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Date getFechaapertura() {
        return this.fechaapertura;
    }
    
    public void setFechaapertura(Date fechaapertura) {
        this.fechaapertura = fechaapertura;
    }
    public Date getFechacierre() {
        return this.fechacierre;
    }
    
    public void setFechacierre(Date fechacierre) {
        this.fechacierre = fechacierre;
    }
    public Double getValorapertura() {
        return this.valorapertura;
    }
    
    public void setValorapertura(Double valorapertura) {
        this.valorapertura = valorapertura;
    }
    public Double getValorcierre() {
        return this.valorcierre;
    }
    
    public void setValorcierre(Double valorcierre) {
        this.valorcierre = valorcierre;
    }
    public Double getSalidas() {
        return this.salidas;
    }
    
    public void setSalidas(Double salidas) {
        this.salidas = salidas;
    }




}


