package co.com.ordersAgiles.entidades;
// Generated 27/02/2015 01:39:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ordbdg generated by hbm2java
 */
public class Ordbdg  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Integer estado;
     private String nombre;
     private String ubicacion;
     private Set<Ordinv> ordinvs = new HashSet<Ordinv>(0);
     private Set<Orddoc> orddocs = new HashSet<Orddoc>(0);

    public Ordbdg() {
    }

	
    public Ordbdg(int id) {
        this.id = id;
    }
    public Ordbdg(int id, String descripcion, Integer estado, String nombre, String ubicacion, Set<Ordinv> ordinvs, Set<Orddoc> orddocs) {
       this.id = id;
       this.descripcion = descripcion;
       this.estado = estado;
       this.nombre = nombre;
       this.ubicacion = ubicacion;
       this.ordinvs = ordinvs;
       this.orddocs = orddocs;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public Set<Ordinv> getOrdinvs() {
        return this.ordinvs;
    }
    
    public void setOrdinvs(Set<Ordinv> ordinvs) {
        this.ordinvs = ordinvs;
    }
    public Set<Orddoc> getOrddocs() {
        return this.orddocs;
    }
    
    public void setOrddocs(Set<Orddoc> orddocs) {
        this.orddocs = orddocs;
    }




}


