package co.com.ordersAgiles.entidades;
// Generated 27/02/2015 01:39:57 PM by Hibernate Tools 4.3.1



/**
 * Orddtl generated by hbm2java
 */
public class Orddtl  implements java.io.Serializable {


     private long id;
     private Ordart ordart;
     private Orddoc orddoc;
     private Integer cantidad;
     private String descripcion;
     private Double descuento;
     private Double descuentoPtj;
     private Integer estado;
     private Double iva;
     private Double ivaPtj;
     private Double retefuente;
     private Double reteica;
     private Double reteiva;
     private Double subtotal;
     private String tipoRetefuente;
     private String tipoReteica;
     private String tipoReteiva;
     private Double total;
     private Double valor;

    public Orddtl() {
    }

	
    public Orddtl(long id) {
        this.id = id;
    }
    public Orddtl(long id, Ordart ordart, Orddoc orddoc, Integer cantidad, String descripcion, Double descuento, Double descuentoPtj, Integer estado, Double iva, Double ivaPtj, Double retefuente, Double reteica, Double reteiva, Double subtotal, String tipoRetefuente, String tipoReteica, String tipoReteiva, Double total, Double valor) {
       this.id = id;
       this.ordart = ordart;
       this.orddoc = orddoc;
       this.cantidad = cantidad;
       this.descripcion = descripcion;
       this.descuento = descuento;
       this.descuentoPtj = descuentoPtj;
       this.estado = estado;
       this.iva = iva;
       this.ivaPtj = ivaPtj;
       this.retefuente = retefuente;
       this.reteica = reteica;
       this.reteiva = reteiva;
       this.subtotal = subtotal;
       this.tipoRetefuente = tipoRetefuente;
       this.tipoReteica = tipoReteica;
       this.tipoReteiva = tipoReteiva;
       this.total = total;
       this.valor = valor;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Ordart getOrdart() {
        return this.ordart;
    }
    
    public void setOrdart(Ordart ordart) {
        this.ordart = ordart;
    }
    public Orddoc getOrddoc() {
        return this.orddoc;
    }
    
    public void setOrddoc(Orddoc orddoc) {
        this.orddoc = orddoc;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Double getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Double descuento) {
        this.descuento = descuento;
    }
    public Double getDescuentoPtj() {
        return this.descuentoPtj;
    }
    
    public void setDescuentoPtj(Double descuentoPtj) {
        this.descuentoPtj = descuentoPtj;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Double getIva() {
        return this.iva;
    }
    
    public void setIva(Double iva) {
        this.iva = iva;
    }
    public Double getIvaPtj() {
        return this.ivaPtj;
    }
    
    public void setIvaPtj(Double ivaPtj) {
        this.ivaPtj = ivaPtj;
    }
    public Double getRetefuente() {
        return this.retefuente;
    }
    
    public void setRetefuente(Double retefuente) {
        this.retefuente = retefuente;
    }
    public Double getReteica() {
        return this.reteica;
    }
    
    public void setReteica(Double reteica) {
        this.reteica = reteica;
    }
    public Double getReteiva() {
        return this.reteiva;
    }
    
    public void setReteiva(Double reteiva) {
        this.reteiva = reteiva;
    }
    public Double getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Double subtotal) {
        this.subtotal = subtotal;
    }
    public String getTipoRetefuente() {
        return this.tipoRetefuente;
    }
    
    public void setTipoRetefuente(String tipoRetefuente) {
        this.tipoRetefuente = tipoRetefuente;
    }
    public String getTipoReteica() {
        return this.tipoReteica;
    }
    
    public void setTipoReteica(String tipoReteica) {
        this.tipoReteica = tipoReteica;
    }
    public String getTipoReteiva() {
        return this.tipoReteiva;
    }
    
    public void setTipoReteiva(String tipoReteiva) {
        this.tipoReteiva = tipoReteiva;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }




}


