package co.com.ordersAgiles.entidades;
// Generated 27/02/2015 01:39:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orddoc generated by hbm2java
 */
public class Orddoc  implements java.io.Serializable {


     private long id;
     private Ordbdg ordbdg;
     private Orddoc orddoc;
     private Ordfrp ordfrp;
     private Ordkja ordkja;
     private Ordter ordterByReceptor;
     private Ordter ordterByEmisor;
     private Integer alerta;
     private String codigo;
     private Double descuento;
     private Integer estado;
     private Date fecha1;
     private Date fecha2;
     private String observaciones;
     private Double retefuente;
     private Double reteica;
     private Double reteiva;
     private Double subtotal;
     private String tipoRetefuente;
     private String tipoReteica;
     private String tipoReteiva;
     private Double total;
     private Double totalIva;
     private String vendedor;
     private Integer tipo;
     private Set<Orddoc> orddocs = new HashSet<Orddoc>(0);
     private Set<Orddtl> orddtls = new HashSet<Orddtl>(0);

    public Orddoc() {
    }

	
    public Orddoc(long id) {
        this.id = id;
    }
    public Orddoc(long id, Ordbdg ordbdg, Orddoc orddoc, Ordfrp ordfrp, Ordkja ordkja, Ordter ordterByReceptor, Ordter ordterByEmisor, Integer alerta, String codigo, Double descuento, Integer estado, Date fecha1, Date fecha2, String observaciones, Double retefuente, Double reteica, Double reteiva, Double subtotal, String tipoRetefuente, String tipoReteica, String tipoReteiva, Double total, Double totalIva, String vendedor, Integer tipo, Set<Orddoc> orddocs, Set<Orddtl> orddtls) {
       this.id = id;
       this.ordbdg = ordbdg;
       this.orddoc = orddoc;
       this.ordfrp = ordfrp;
       this.ordkja = ordkja;
       this.ordterByReceptor = ordterByReceptor;
       this.ordterByEmisor = ordterByEmisor;
       this.alerta = alerta;
       this.codigo = codigo;
       this.descuento = descuento;
       this.estado = estado;
       this.fecha1 = fecha1;
       this.fecha2 = fecha2;
       this.observaciones = observaciones;
       this.retefuente = retefuente;
       this.reteica = reteica;
       this.reteiva = reteiva;
       this.subtotal = subtotal;
       this.tipoRetefuente = tipoRetefuente;
       this.tipoReteica = tipoReteica;
       this.tipoReteiva = tipoReteiva;
       this.total = total;
       this.totalIva = totalIva;
       this.vendedor = vendedor;
       this.tipo = tipo;
       this.orddocs = orddocs;
       this.orddtls = orddtls;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Ordbdg getOrdbdg() {
        return this.ordbdg;
    }
    
    public void setOrdbdg(Ordbdg ordbdg) {
        this.ordbdg = ordbdg;
    }
    public Orddoc getOrddoc() {
        return this.orddoc;
    }
    
    public void setOrddoc(Orddoc orddoc) {
        this.orddoc = orddoc;
    }
    public Ordfrp getOrdfrp() {
        return this.ordfrp;
    }
    
    public void setOrdfrp(Ordfrp ordfrp) {
        this.ordfrp = ordfrp;
    }
    public Ordkja getOrdkja() {
        return this.ordkja;
    }
    
    public void setOrdkja(Ordkja ordkja) {
        this.ordkja = ordkja;
    }
    public Ordter getOrdterByReceptor() {
        return this.ordterByReceptor;
    }
    
    public void setOrdterByReceptor(Ordter ordterByReceptor) {
        this.ordterByReceptor = ordterByReceptor;
    }
    public Ordter getOrdterByEmisor() {
        return this.ordterByEmisor;
    }
    
    public void setOrdterByEmisor(Ordter ordterByEmisor) {
        this.ordterByEmisor = ordterByEmisor;
    }
    public Integer getAlerta() {
        return this.alerta;
    }
    
    public void setAlerta(Integer alerta) {
        this.alerta = alerta;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Double getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Double descuento) {
        this.descuento = descuento;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Date getFecha1() {
        return this.fecha1;
    }
    
    public void setFecha1(Date fecha1) {
        this.fecha1 = fecha1;
    }
    public Date getFecha2() {
        return this.fecha2;
    }
    
    public void setFecha2(Date fecha2) {
        this.fecha2 = fecha2;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Double getRetefuente() {
        return this.retefuente;
    }
    
    public void setRetefuente(Double retefuente) {
        this.retefuente = retefuente;
    }
    public Double getReteica() {
        return this.reteica;
    }
    
    public void setReteica(Double reteica) {
        this.reteica = reteica;
    }
    public Double getReteiva() {
        return this.reteiva;
    }
    
    public void setReteiva(Double reteiva) {
        this.reteiva = reteiva;
    }
    public Double getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Double subtotal) {
        this.subtotal = subtotal;
    }
    public String getTipoRetefuente() {
        return this.tipoRetefuente;
    }
    
    public void setTipoRetefuente(String tipoRetefuente) {
        this.tipoRetefuente = tipoRetefuente;
    }
    public String getTipoReteica() {
        return this.tipoReteica;
    }
    
    public void setTipoReteica(String tipoReteica) {
        this.tipoReteica = tipoReteica;
    }
    public String getTipoReteiva() {
        return this.tipoReteiva;
    }
    
    public void setTipoReteiva(String tipoReteiva) {
        this.tipoReteiva = tipoReteiva;
    }
    public Double getTotal() {
        return this.total;
    }
    
    public void setTotal(Double total) {
        this.total = total;
    }
    public Double getTotalIva() {
        return this.totalIva;
    }
    
    public void setTotalIva(Double totalIva) {
        this.totalIva = totalIva;
    }
    public String getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(String vendedor) {
        this.vendedor = vendedor;
    }
    public Integer getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }
    public Set<Orddoc> getOrddocs() {
        return this.orddocs;
    }
    
    public void setOrddocs(Set<Orddoc> orddocs) {
        this.orddocs = orddocs;
    }
    public Set<Orddtl> getOrddtls() {
        return this.orddtls;
    }
    
    public void setOrddtls(Set<Orddtl> orddtls) {
        this.orddtls = orddtls;
    }




}


