package co.com.ordersAgiles.entidades;
// Generated 27/02/2015 01:39:57 PM by Hibernate Tools 4.3.1



/**
 * Ordinv generated by hbm2java
 */
public class Ordinv  implements java.io.Serializable {


     private OrdinvId id;
     private Ordart ordart;
     private Ordbdg ordbdg;
     private Integer cantidad;
     private Integer estado;
     private Integer stockalerta;
     private Integer stockmax;
     private Integer stockmin;

    public Ordinv() {
    }

	
    public Ordinv(OrdinvId id, Ordart ordart, Ordbdg ordbdg) {
        this.id = id;
        this.ordart = ordart;
        this.ordbdg = ordbdg;
    }
    public Ordinv(OrdinvId id, Ordart ordart, Ordbdg ordbdg, Integer cantidad, Integer estado, Integer stockalerta, Integer stockmax, Integer stockmin) {
       this.id = id;
       this.ordart = ordart;
       this.ordbdg = ordbdg;
       this.cantidad = cantidad;
       this.estado = estado;
       this.stockalerta = stockalerta;
       this.stockmax = stockmax;
       this.stockmin = stockmin;
    }
   
    public OrdinvId getId() {
        return this.id;
    }
    
    public void setId(OrdinvId id) {
        this.id = id;
    }
    public Ordart getOrdart() {
        return this.ordart;
    }
    
    public void setOrdart(Ordart ordart) {
        this.ordart = ordart;
    }
    public Ordbdg getOrdbdg() {
        return this.ordbdg;
    }
    
    public void setOrdbdg(Ordbdg ordbdg) {
        this.ordbdg = ordbdg;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Integer getStockalerta() {
        return this.stockalerta;
    }
    
    public void setStockalerta(Integer stockalerta) {
        this.stockalerta = stockalerta;
    }
    public Integer getStockmax() {
        return this.stockmax;
    }
    
    public void setStockmax(Integer stockmax) {
        this.stockmax = stockmax;
    }
    public Integer getStockmin() {
        return this.stockmin;
    }
    
    public void setStockmin(Integer stockmin) {
        this.stockmin = stockmin;
    }




}


