package co.com.ordersAgiles.entidades;
// Generated 27/02/2015 01:39:57 PM by Hibernate Tools 4.3.1



/**
 * OrdinvId generated by hbm2java
 */
public class OrdinvId  implements java.io.Serializable {


     private long articulo;
     private int bodega;

    public OrdinvId() {
    }

    public OrdinvId(long articulo, int bodega) {
       this.articulo = articulo;
       this.bodega = bodega;
    }
   
    public long getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(long articulo) {
        this.articulo = articulo;
    }
    public int getBodega() {
        return this.bodega;
    }
    
    public void setBodega(int bodega) {
        this.bodega = bodega;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrdinvId) ) return false;
		 OrdinvId castOther = ( OrdinvId ) other; 
         
		 return (this.getArticulo()==castOther.getArticulo())
 && (this.getBodega()==castOther.getBodega());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getArticulo();
         result = 37 * result + this.getBodega();
         return result;
   }   


}


