package co.com.ordersAgiles.entidades;
// Generated 27/02/2015 01:39:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ordktg generated by hbm2java
 */
public class Ordktg  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Integer estado;
     private String nombre;
     private Set<Ordart> ordarts = new HashSet<Ordart>(0);

    public Ordktg() {
    }

	
    public Ordktg(int id) {
        this.id = id;
    }
    public Ordktg(int id, String descripcion, Integer estado, String nombre, Set<Ordart> ordarts) {
       this.id = id;
       this.descripcion = descripcion;
       this.estado = estado;
       this.nombre = nombre;
       this.ordarts = ordarts;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Ordart> getOrdarts() {
        return this.ordarts;
    }
    
    public void setOrdarts(Set<Ordart> ordarts) {
        this.ordarts = ordarts;
    }




}


