package co.com.ordersAgiles.entidades;
// Generated 27/02/2015 01:39:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ordprf generated by hbm2java
 */
public class Ordprf  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Integer estado;
     private String nombre;
     private Set<Ordprm> ordprms = new HashSet<Ordprm>(0);
     private Set<Ordusr> ordusrs = new HashSet<Ordusr>(0);

    public Ordprf() {
    }

	
    public Ordprf(int id) {
        this.id = id;
    }
    public Ordprf(int id, String descripcion, Integer estado, String nombre, Set<Ordprm> ordprms, Set<Ordusr> ordusrs) {
       this.id = id;
       this.descripcion = descripcion;
       this.estado = estado;
       this.nombre = nombre;
       this.ordprms = ordprms;
       this.ordusrs = ordusrs;
    }
    
    public Ordprf(int id, String descripcion, Integer estado, String nombre) {
       this.id = id;
       this.descripcion = descripcion;
       this.estado = estado;
       this.nombre = nombre;
       
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Ordprm> getOrdprms() {
        return this.ordprms;
    }
    
    public void setOrdprms(Set<Ordprm> ordprms) {
        this.ordprms = ordprms;
    }
    public Set<Ordusr> getOrdusrs() {
        return this.ordusrs;
    }
    
    public void setOrdusrs(Set<Ordusr> ordusrs) {
        this.ordusrs = ordusrs;
    }

    @Override
    public String toString() {
        return "Ordprf{" + "id=" + id + ", descripcion=" + descripcion + ", estado=" + estado + ", nombre=" + nombre + ", ordprms=" + ordprms + ", ordusrs=" + ordusrs + '}';
    }


}


