package co.com.ordersAgiles.entidades;
// Generated 27/02/2015 01:39:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ordter generated by hbm2java
 */
public class Ordter  implements java.io.Serializable {


     private int id;
     private String apellidos;
     private Integer digitoverificacion;
     private String direccion;
     private Integer estado;
     private String nombres;
     private String numeroid;
     private Integer tipo;
     private String tipoid;
     private String telefonos;
     private String correos;
     private Set<Orddoc> orddocsForReceptor = new HashSet<Orddoc>(0);
     private Set<Orddoc> orddocsForEmisor = new HashSet<Orddoc>(0);
     private Set<Ordusr> ordusrs = new HashSet<Ordusr>(0);

    public Ordter() {
    }

	
    public Ordter(int id) {
        this.id = id;
    }
    public Ordter(int id, String apellidos, Integer digitoverificacion, String direccion, Integer estado, String nombres, String numeroid, Integer tipo, String tipoid, String telefonos, String correos, Set<Orddoc> orddocsForReceptor, Set<Orddoc> orddocsForEmisor, Set<Ordusr> ordusrs) {
       this.id = id;
       this.apellidos = apellidos;
       this.digitoverificacion = digitoverificacion;
       this.direccion = direccion;
       this.estado = estado;
       this.nombres = nombres;
       this.numeroid = numeroid;
       this.tipo = tipo;
       this.tipoid = tipoid;
       this.telefonos = telefonos;
       this.correos = correos;
       this.orddocsForReceptor = orddocsForReceptor;
       this.orddocsForEmisor = orddocsForEmisor;
       this.ordusrs = ordusrs;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Integer getDigitoverificacion() {
        return this.digitoverificacion;
    }
    
    public void setDigitoverificacion(Integer digitoverificacion) {
        this.digitoverificacion = digitoverificacion;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getNumeroid() {
        return this.numeroid;
    }
    
    public void setNumeroid(String numeroid) {
        this.numeroid = numeroid;
    }
    public Integer getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }
    public String getTipoid() {
        return this.tipoid;
    }
    
    public void setTipoid(String tipoid) {
        this.tipoid = tipoid;
    }
    public String getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(String telefonos) {
        this.telefonos = telefonos;
    }
    public String getCorreos() {
        return this.correos;
    }
    
    public void setCorreos(String correos) {
        this.correos = correos;
    }
    public Set<Orddoc> getOrddocsForReceptor() {
        return this.orddocsForReceptor;
    }
    
    public void setOrddocsForReceptor(Set<Orddoc> orddocsForReceptor) {
        this.orddocsForReceptor = orddocsForReceptor;
    }
    public Set<Orddoc> getOrddocsForEmisor() {
        return this.orddocsForEmisor;
    }
    
    public void setOrddocsForEmisor(Set<Orddoc> orddocsForEmisor) {
        this.orddocsForEmisor = orddocsForEmisor;
    }
    public Set<Ordusr> getOrdusrs() {
        return this.ordusrs;
    }
    
    public void setOrdusrs(Set<Ordusr> ordusrs) {
        this.ordusrs = ordusrs;
    }




}


