package co.com.ordersAgiles.entidades;
// Generated 27/02/2015 01:39:57 PM by Hibernate Tools 4.3.1



/**
 * TiposDocumento generated by hbm2java
 */
public class TiposDocumento  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private Integer estado;
     private String formatoCodigo;
     private Integer impactoInventario;
     private Long indice;
     private String nombre;

    public TiposDocumento() {
    }

	
    public TiposDocumento(int id) {
        this.id = id;
    }
    public TiposDocumento(int id, String descripcion, Integer estado, String formatoCodigo, Integer impactoInventario, Long indice, String nombre) {
       this.id = id;
       this.descripcion = descripcion;
       this.estado = estado;
       this.formatoCodigo = formatoCodigo;
       this.impactoInventario = impactoInventario;
       this.indice = indice;
       this.nombre = nombre;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public String getFormatoCodigo() {
        return this.formatoCodigo;
    }
    
    public void setFormatoCodigo(String formatoCodigo) {
        this.formatoCodigo = formatoCodigo;
    }
    public Integer getImpactoInventario() {
        return this.impactoInventario;
    }
    
    public void setImpactoInventario(Integer impactoInventario) {
        this.impactoInventario = impactoInventario;
    }
    public Long getIndice() {
        return this.indice;
    }
    
    public void setIndice(Long indice) {
        this.indice = indice;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


